### ISSUE TITLE
Classe DPE null si pas de valeur forfaitaire trouvée pour rendement_generation ch

### ISSUE THREAD

**Issue by michaeldesigaud** [jzck/Open3CL#47]
**Describe the bug**
Pour certains DPE on ne trouve aucune occurrence dans la table de valeur `rendement_generation` ce qui a pour conséquence que la valeur `rg` est non définie et donc la valeur `ch` non plus et on se retrouve avec une classe DPE nulle.

```javascript
if (row) {
    di.rendement_generation = Number(row.rg);
    di.rg = di.rendement_generation;
    di.rg_dep = di.rendement_generation;
    de.tv_rendement_generation_id = Number(row.tv_rendement_generation_id);
  } else {
    console.error('!! pas de valeur forfaitaire trouvée pour rendement_generation ch !!');
  }
```

Est il possible dans ce cas là de fournir une valeur `rg` moyenne ou mettre `0` ?

**To Reproduce**
2287E0839803N

**Expected behavior**
Avoir une classe DPE de sortie même lorsque l'on ne trouve pas de valeur forfaitaire pour le rendement

**Additional context**

- NodeJS version: 20.12.0

**Comment by jzck** [comment]
Je ne comprends pas bien, pour le dpe `2287E0839803N` on trouve bien une etiquette E, comme le calcul original de Liciel.

**Comment by michaeldesigaud** [comment]
Désolé le problème était de notre coté, je cloture l'issue
