### ISSUE TITLE
Erreur lors de la saisie manuelle de la valeur uph_saisi

### ISSUE THREAD

**Issue by michaeldesigaud** [jzck/Open3CL#48]
**Describe the bug**
En cas de saisie manuelle (`enum_methode_saisie_u_id: 9`) de la valuer `uph_saisi`, elle ne semble pas lue, une erreur apparait `requestInput: type is not defined for uph_saisi`. 

En effet dans `3.2.2_plancher_haut.js` on a : 
```javascript
case 'saisie direct u depuis rset/rsee( etude rt2012/re2020)':
      di.uph = requestInput(de, du, 'uph_saisi');
      break;
```

Si on compare à `3.2.2_plancher_bas.js` on a : 

```javascript
 case 'saisie direct u depuis rset/rsee( etude rt2012/re2020)':
      di.upb = requestInput(de, du, 'upb_saisi', 'float');
      break;
```

Dans `3.2.2_plancher_haut.js`, faut il rajouter le type `float` comme argument ?

**To Reproduce**
2287E0839803N

**Expected behavior**
Pouvoir saisi manuellement la valeur uph

**Additional context**

- NodeJS version: 20.1.20

**Comment by jzck** [comment]
Oui il doit surement falloir faire comme pour upb
