### ISSUE TITLE
Erreur dans qualité d'isolation, DR n'est pas pris en compte dans le calcul de dep

### ISSUE THREAD

**Issue by dorianboille** [jzck/Open3CL#54]
Erreur dans la formule des déperditions dans le fichier `Open3CL\src\2021_04_13_qualite_isolation.js`

Les déperditions sont calculées avec
```
const dep =
    dp.deperdition_mur +
    dp.deperdition_plancher_bas +
    dp.deperdition_plancher_haut +
    dp.deperdition_baie_vitree +
    dp.deperdition_porte +
    dp.deperdition_pont_thermique;
```
Avec ce calcul, j'obtiens 
```
{
  "ubat": 0.569189431903854,
  "qualite_isol_enveloppe": 2,
  "qualite_isol_mur": 4,
  "qualite_isol_plancher_bas": 4,
  "qualite_isol_menuiserie": 2,
  "qualite_isol_plancher_haut_comble_perdu": 4
}
```

Or dans mon vrai DPE, j'ai
```
"qualite_isolation": {
        "ubat": 0.8518951612903227,
        "qualite_isol_enveloppe": 4,
        "qualite_isol_mur": 4,
        "qualite_isol_plancher_haut_comble_perdu": 1,
        "qualite_isol_plancher_bas": 4,
        "qualite_isol_menuiserie": 2
      }
```

Le Ubat est donc très différent.

**Potentielle solution**
Dans la méthode 3CL, la déperdition de l'enveloppe se calcul comme ca :
![image](https://github.com/user-attachments/assets/c7d11f5a-1fd7-4905-8d8b-bb4bba1fbdb3)

Il faudrait donc rajouter le `+ DR` dans le calcul.

Si je rajoute `deperdition_renouvellement_air` dans le calcul de `dep`, j'obtiens Ubat = 0.86, soit quasiment la valeur dans mon vrai DPE.

Cependant, je ne trouve pas sur internet la méthode de calcul pour le confort d'été et la performance de l'isolation.

**Comment by michaeldesigaud** [comment]
Merci pour le retour, tu peux faire une PR ?

**Comment by dorianboille** [comment]
Je n'ai pas la permission de push ma branche

**Comment by michaeldesigaud** [comment]
oui il faut faire un fork, pousser la branche dans ton repo forké et faire une PR de ton fork vers cette lib

**Comment by jzck** [comment]
Salut! merci pour l'issue, est-ce que tu pourrais nous partager l'id de ton DPE?
