### ISSUE TITLE
Erreur de calcul des déperditions plancher_haut - période d'isolation connue 

### ISSUE THREAD

**Issue by jgavignet** [jzck/Open3CL#62]
**Describe the bug**
Dans le cas ''année de construction saisie (table forfaitaire)'', la période d'isolation est parfois connue et doit être prise en compte à la place de l'année de construction.

**To Reproduce**
DPE 2287E1724516Y -> deperdition_plancher_haut = 46.80

**Expected behavior**
deperdition_plancher_haut = 112.32

**Additional context**

- NodeJS version: [e.g. 18.16.0]

**Comment by jzck** [comment]
pour `2287E1724516Y`, sur la branche `main`, on trouve bien ` deperdition_plancher_haut: 112.32` non?

**Comment by jgavignet** [comment]
Sur main je trouve pour ce DPE 2287E1724516Y 46.800000000000004 pour deperdition_plancher_haut (sans le mode de comptabilité bug_for_bug_compat). En utilisant le test "Test Open3CL engine compliance on corpus" > "check "deperdition.%s" value"
