### ISSUE TITLE
Documenter que l'installation de `bun` est requise pour `test.sh`

### ISSUE THREAD

**Issue by mbideau** [jzck/Open3CL#79]
**Describe the bug**
Lors du lancement du script `test/test.sh` une erreur indique que l'exécutable `bun` n'est pas trouvé.
Je suppose que `bun` est l'exécutable dont la page web est celle-ci: https://bun.sh/

**To Reproduce**
Lancer le script `test/test.sh _download_one <DPE> ` ou bien directement l'un des scripts JS `test/run_one_dpe.js` ou `test/xml_to_json.js`. 

**Expected behavior**
Ne pas avoir d'erreur et obtenir l'information liée au traitement sélectionné.

La commande suivante permet d'éviter l'installation de `bun`:
```
$ sudo ln -s /usr/bin/node /usr/local/bin/bun
```

- NodeJS version: 22.8.0

**Comment by jzck** [comment]
Salut, comme je ne compte pas garder test.sh dans le futur je close cette issue, l'idée est d'avoir un cli plus propre et mieux documenté
